### ISSUE TITLE
Statistics can't be calculated in lates Emby release

### ISSUE THREAD

**Issue by ChristophCaina** [mregni/statistics-for-emby-server-CORE#2]
Hi, as per discussions in the Emby community, I have decided to create an issue here.
I know, you are currently working on the statistics server, but maybe, you will find some time to see, if you can fix this issue.

I have also forked your statistics plugin and will see, if I can dig into it ... :)

```
2019-08-03 09:28:19.816 Error TaskManager: Error
	*** Error Report ***
	Version: 4.2.0.40
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.18.12
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.InvalidOperationException: System.InvalidOperationException: Sequence contains no elements
	   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
	   at Statistics.Helpers.Calculator.CalculateOldestMovie()
	   at Statistics.ScheduledTasks.CalculateStatsTask.MediaBrowser.Model.Tasks.IScheduledTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
	   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
	Source: System.Linq
	TargetSite: TSource Aggregate[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`3[TSource,TSource,TSource])
	
2019-08-03 09:28:19.816 Info TaskManager: Calculate statistics for all users Failed after 0 minute(s) and 6 seconds
2019-08-03 09:28:19.817 Info TaskManager: ExecuteQueuedTasks
```

**Comment by hackthis02** [comment]
Due to the age of this issue and this branch no longer being maintained. I'm going to close this. If it's still an happening, post an issue here [hackthis02/statistics-for-emby-server-CORE](https://github.com/hackthis02/statistics-for-emby-server-CORE)
